window.PERINI_IMAGES={
  brand:{
    logo:'assets/brand/logo-colegio-perini-cropped.webp'
  },
  hero:{
    desktop:'assets/hero/fachada-perini-desktop.webp',
    mobile:'assets/hero/fachada-perini-mobile.webp',
    jornada:'assets/hero/jornada-perini.webp'
  },
  ensino:{
    fundamental1:'assets/ensino/fundamental-1.webp',
    fundamental2:'assets/ensino/fundamental-2.webp',
    ensinoMedio:'assets/ensino/ensino-medio.webp'
  },
  reais:{
    direcao:'assets/reais/colegio-perini-direcao.webp',
    diretora:'assets/reais/colegio-perini-diretora.webp',
    teatroPalco:'assets/reais/colegio-perini-teatro-palco.webp',
    teatroFundamental:'assets/reais/colegio-perini-teatro-fundamental.webp',
    grupoTeatro:'assets/reais/colegio-perini-grupo-teatro.webp',
    equipeEvento:'assets/reais/colegio-perini-equipe-evento.webp',
    convivencia:'assets/reais/colegio-perini-convivencia.webp',
    trabalhoCampo:'assets/reais/colegio-perini-trabalho-de-campo.webp',
    feiraNacoes:'assets/reais/novas/feira-das-nacoes.webp',
    animaliaGrupo:'assets/reais/novas/animalia-grupo.webp',
    animaliaGrupoMisto:'assets/reais/novas/animalia-grupo-misto.webp',
    cienciaLaboratorio:'assets/reais/novas/ciencia-laboratorio.webp',
    cienciaDetalhe:'assets/reais/novas/ciencia-detalhe.webp',
    arteMaos:'assets/reais/novas/arte-maos.webp',
    mapaGigante:'assets/reais/novas/mapa-gigante.webp',
    liderancaDupla:'assets/reais/novas/lideranca-dupla.webp',
    diretoraEscritorio:'assets/reais/novas/diretora-escritorio.webp'
  }
};
