window.PERINI_IMAGES={
  brand:{logo:'assets/brand/logo-colegio-perini-cropped.webp'},
  hero:{desktop:'assets/hero/fachada-perini-desktop.webp',mobile:'assets/hero/fachada-perini-mobile.webp'},
  ensino:{
    anosIniciais:'assets/ensino/fundamental-1.webp',
    anosFinais:'assets/ensino/fundamental-2.webp',
    ensinoMedio:'assets/ensino/ensino-medio.webp'
  },
  reais:{
    direcao:'assets/reais/colegio-perini-direcao.webp',
    grupoTeatro:'assets/reais/colegio-perini-grupo-teatro.webp',
    teatroAnosIniciais:'assets/reais/colegio-perini-teatro-fundamental-card.webp',
    convivencia:'assets/reais/colegio-perini-convivencia-card.webp',
    equipeEvento:'assets/reais/colegio-perini-equipe-evento-card.webp',
    trabalhoCampo:'assets/reais/colegio-perini-trabalho-de-campo.webp',
    feiraNacoes:'assets/reais/novas/feira-das-nacoes.webp',
    animaliaGrupo:'assets/reais/novas/animalia-grupo.webp',
    animaliaGrupoMisto:'assets/reais/novas/animalia-grupo-misto.webp',
    cienciaLaboratorio:'assets/reais/novas/ciencia-laboratorio.webp',
    cienciaDetalhe:'assets/reais/novas/ciencia-detalhe.webp',
    arteMaos:'assets/reais/novas/arte-maos.webp',
    mapaGigante:'assets/reais/novas/mapa-gigante.webp',
    diretoraEscritorio:'assets/reais/novas/diretora-escritorio.webp',
    liderancaDupla:'assets/reais/novas/lideranca-dupla.webp'
  }
};
